variables {
  os_distribution      = "ubuntu24"
  sizing_profile       = "pro-ultimate"
  jump_host_ip         = "10.10.10.80"
  control_plane_ips    = ["10.10.10.81"]
  control_plane_vip    = "10.10.10.85"
  worker_ips           = ["10.10.10.86"]
  network_gateway      = "10.10.10.1"
  dns_servers          = ["10.10.10.1"]
  ssh_public_key       = "ssh-ed25519 AAAAexample user@laptop \n"
  provider_name        = "test"
  nic_name             = "ens192"
  nic_comment          = "Test NIC name"
  disk_comment         = "Ceph {ceph_gb} GB, volumes {volume_gb} GB"
  ceph_osd_device      = "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0"
  local_volume_devices = ["/dev/v1", "/dev/v2", "/dev/v3", "/dev/v4"]
}

run "pro_ultimate_sizes" {
  command = plan
  assert {
    condition     = output.sizing.worker_cores == 8 && output.sizing.worker_memory == 32768 && output.sizing.control_plane_memory == 16384
    error_message = "pro-ultimate must match the NKP 2.18 Pro/Ultimate table"
  }
  assert {
    condition     = output.sizing.ceph_disk_gb == 50 && output.sizing.local_volume_gb == 110
    error_message = "pro-ultimate disk sizes changed"
  }
}

run "contract_test_with_override" {
  command = plan
  variables {
    sizing_profile    = "contract-test"
    ceph_disk_size_gb = 7
  }
  assert {
    condition     = output.sizing.worker_cores == 2 && output.sizing.ceph_disk_gb == 7 && output.sizing.local_volume_gb == 5
    error_message = "contract-test sizes or the Ceph override are wrong"
  }
}

run "single_node_names" {
  command = plan
  assert {
    condition     = output.control_plane_names == ["nkp-cp-01"] && output.worker_names == ["nkp-worker-01"] && length(output.hosts) == 3
    error_message = "names for 1 control plane and 1 worker are wrong"
  }
}

run "cloud_init_content" {
  command = plan
  assert {
    condition     = startswith(output.cloud_init["nkp-worker-01"].user_data, "#cloud-config\n")
    error_message = "user-data must start with #cloud-config"
  }
  assert {
    condition     = yamldecode(output.cloud_init["nkp-worker-01"].user_data).users[0].ssh_authorized_keys[0] == "ssh-ed25519 AAAAexample user@laptop"
    error_message = "the SSH key must be trimmed"
  }
  assert {
    condition     = yamldecode(output.cloud_init["nkp-worker-01"].network_config).ethernets["ens192"].addresses[0] == "10.10.10.86/24"
    error_message = "network-config must carry the static address on nic_name"
  }
  assert {
    condition     = strcontains(output.user_data_with_network["nkp-worker-01"], "/etc/netplan/60-nkp.yaml")
    error_message = "Ubuntu user-data must write the netplan file"
  }
}

run "rocky_network_keyfile" {
  command = plan
  variables {
    os_distribution = "rocky9"
  }
  assert {
    condition     = strcontains(output.user_data_with_network["nkp-cp-01"], "address1=10.10.10.81/24,10.10.10.1")
    error_message = "Rocky user-data must write the NetworkManager keyfile"
  }
}

run "inventory_text" {
  command = plan
  assert {
    condition     = strcontains(output.ansible_inventory, "virtual_ip_interface = ens192\n") && strcontains(output.ansible_inventory, "ceph_osd_device = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0\n")
    error_message = "inventory must carry the provider NIC and disk paths"
  }
  assert {
    condition     = strcontains(output.ansible_inventory, "# Ceph 50 GB, volumes 110 GB\n") && strcontains(output.ansible_inventory, "# Generated by tofu/test for os_distribution=ubuntu24,")
    error_message = "inventory comments are wrong"
  }
}

run "rejects_two_control_planes" {
  command = plan
  variables {
    control_plane_ips = ["10.10.10.81", "10.10.10.82"]
  }
  expect_failures = [var.control_plane_ips]
}

run "rejects_three_volumes" {
  command = plan
  variables {
    local_volume_devices = ["/dev/v1", "/dev/v2", "/dev/v3"]
  }
  expect_failures = [var.local_volume_devices]
}

# The static address written by user-data must not depend on the NIC name,
# which differs between images (Rocky GenericCloud boots with net.ifnames=0).
run "network_files_do_not_depend_on_the_nic_name" {
  command = plan
  variables {
    os_distribution = "rocky9"
  }
  assert {
    condition     = !strcontains(output.user_data_with_network["nkp-worker-01"], "interface-name=") && !strcontains(output.user_data_with_network["nkp-worker-01"], "ens192")
    error_message = "the NetworkManager keyfile must not be bound to an interface name"
  }
}

run "netplan_matches_any_ethernet_name" {
  command = plan
  assert {
    condition     = strcontains(output.user_data_with_network["nkp-worker-01"], "\"name\": \"e*\"") && !strcontains(output.user_data_with_network["nkp-worker-01"], "ens192")
    error_message = "the netplan file must match the NIC by a name pattern"
  }
}

# RHEL-family cloud-init prefers the FQDN, and Nutanix ConfigDrive metadata
# says "localhost": both documents must set fqdn to the VM name.
run "user_data_sets_the_fqdn" {
  command = plan
  assert {
    condition     = yamldecode(output.cloud_init["nkp-worker-01"].user_data).fqdn == "nkp-worker-01" && yamldecode(output.user_data_with_network["nkp-cp-01"]).fqdn == "nkp-cp-01"
    error_message = "user-data must set fqdn to the VM name"
  }
}

# cloud-init on Rocky converts the v2 network config itself and rejects the
# netplan-only route destination "default" (traceback in _normalize_route, no
# address configured): the default route is written as 0.0.0.0/0.
run "network_config_default_route_is_a_cidr" {
  command = plan
  assert {
    condition     = yamldecode(output.cloud_init["nkp-worker-01"].network_config).ethernets["ens192"].routes[0].to == "0.0.0.0/0"
    error_message = "the NoCloud default route must be 0.0.0.0/0"
  }
}

# Address mistakes stop the plan before anything is created: the format of
# each address in the variable validations, duplicates and a VIP equal to a
# node in a precondition of output.sizing, which every module reads first.
run "rejects_a_malformed_address" {
  command = plan
  variables {
    worker_ips = ["10.10.10.8l"]
  }
  expect_failures = [var.worker_ips]
}

run "rejects_a_malformed_jump_host_address" {
  command = plan
  variables {
    jump_host_ip = "10.10.10.300"
  }
  expect_failures = [var.jump_host_ip]
}

run "rejects_a_malformed_gateway" {
  command = plan
  variables {
    network_gateway = "gateway"
  }
  expect_failures = [var.network_gateway]
}

run "rejects_an_address_used_twice" {
  command = plan
  variables {
    worker_ips = ["10.10.10.86", "10.10.10.81"]
  }
  expect_failures = [output.sizing]
}

run "rejects_a_vip_equal_to_a_node" {
  command = plan
  variables {
    control_plane_vip = "10.10.10.81"
  }
  expect_failures = [output.sizing]
}

run "rejects_a_prefix_out_of_range" {
  command = plan
  variables {
    network_prefix_length = 33
  }
  expect_failures = [var.network_prefix_length]
}
